version: "3"

tasks:
  
  parse_vad:
    silent: true
    cmds:
      - python parsers/parse_vad.py -i ../samples/vad_2/vad_2.graphml -o ../samples/vad_2/vad_2.ttl

  validate_vad_ttl:
    silent: true
    cmds:
      - ttl ../samples/vad_2/vad_2.ttl
